### ISSUE TITLE
gunicorn does not fully reload and does not rebuild pyc files

### ISSUE THREAD

**Issue by plyd** [sloria/aiohttp_utils#5]
Hello Sloria,
I'm not sure this problem is linked directly to `gunicorn` or to `aiohttp_utils` library as Udi suggests on this [StackOverflow question](https://stackoverflow.com/questions/42631043/aiohttp-utils-gunicorn-doesnt-fully-reload-and-doesnt-rebuild-pyc-files).
Maybe you could help me figure out?
Thank you!

**Comment by sloria** [comment]
Yes, the implementation of `aiohttp_utils.runner` is incomplete, and I am no longer supporting it. I have added a DeprecationWarning, and I recommend using the `adev runserver` command from [aiohttp-devtools](https://github.com/aio-libs/aiohttp-devtools) instead.
