### ISSUE TITLE
Is content negotiation not supported on Windows?

### ISSUE THREAD

**Issue by sanderzz91** [sloria/aiohttp_utils#6]
Hi,

I was just trying to set up content negotiation in my aiohttp web application. On launching my app, I got this error:

```
Traceback (most recent call last):
  File "C:/Users/Sander/dynamic-dashboard/sensor_gateway/main.py", line 4, in <module>
    from aiohttp_utils import negotiation
  File "C:\ProgramData\Anaconda3\envs\sensor_gateway\lib\site-packages\aiohttp_utils\__init__.py", line 4, in <module>
    from .runner import run
  File "C:\ProgramData\Anaconda3\envs\sensor_gateway\lib\site-packages\aiohttp_utils\runner.py", line 20, in <module>
    from aiohttp.worker import GunicornWebWorker as BaseWorker
  File "C:\ProgramData\Anaconda3\envs\sensor_gateway\lib\site-packages\aiohttp\worker.py", line 10, in <module>
    from gunicorn.config import AccessLogFormat as GunicornAccessLogFormat
  File "C:\ProgramData\Anaconda3\envs\sensor_gateway\lib\site-packages\gunicorn\config.py", line 9, in <module>
    import grp
ModuleNotFoundError: No module named 'grp'

Process finished with exit code 1
```
I found it strange that this dependency module did not get installed in the first place, when I installed aiohttp_utils. So I have just run the pip install of grp and I got this error:

```
Collecting grp
  Could not find a version that satisfies the requirement grp (from versions: )
No matching distribution found for grp
```

My development platform is Windows x64, and that's of course the platform on which I first run tests before putting the app in production.
I see though that this grp module actually is a Unix thing:

> This module provides access to the Unix group database. It is available on all Unix versions.
(from https://docs.python.org/2/library/grp.html)

So, is it actually impossible to use aiohttp_utils on Windows? I must set up content negotiation in my app, but I preferred using a library if possible, instead of using if-else constructions in my view handlers based on the Accept HTTP header.

To be sure that, if some other package problem is at the root of this problem, instead of just my platform, I post my virtual environment (conda) setup too:

```
name: sensor_gateway
channels:
  - defaults
dependencies:
  - aiohttp=2.3.9=py36_0
  - async-timeout=2.0.0=py36hc3e01a3_0
  - certifi=2018.1.18=py36_0
  - chardet=3.0.4=py36h420ce6e_1
  - jinja2=2.10=py36h292fed1_0
  - markupsafe=1.0=py36h0e26971_1
  - multidict=3.3.2=py36h72bac45_0
  - pip=9.0.1=py36h226ae91_4
  - pymysql=0.7.11=py36hf59f3ba_0
  - python=3.6.4=h6538335_1
  - pytz=2018.3=py36_0
  - setuptools=38.4.0=py36_0
  - sqlalchemy=1.2.1=py36hfa6e2cd_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.0.25123=3
  - wheel=0.30.0=py36h6c3ec14_1
  - wincertstore=0.2=py36h7fe50ca_0
  - yarl=0.14.2=py36h27d1bf2_0
  - pip:
    - aiohttp-jinja2==0.16.0
    - aiohttp-utils==3.0.0
    - aiomysql==0.0.12
    - attrs==17.4.0
    - gunicorn==19.7.1
    - idna==2.6
    - idna-ssl==1.0.0
    - python-mimeparse==1.6.0
prefix: C:\ProgramData\Anaconda3\envs\sensor_gateway
```

Thanks in advance for any help.

**Comment by NewUserHa** [comment]
+1

**Comment by sloria** [comment]
I doubt that the issue is specific to this library, since there is no code that is platform-specific.  Perhaps something with your version of gunicorn?

I'm sorry but I don't have time to look further into the issue. Please feel free to comment here if you discover anything new.

**Comment by NewUserHa** [comment]
new installed `aiohttp_utils` and `aiohttp`.
`aiohttp_utils.run(app)`  output `ModuleNotFoundError: No module named 'grp'`
