### ISSUE TITLE
Does using aiohttp_utils mean I must deploy my app with Nginx+Gunicorn?

### ISSUE THREAD

**Issue by sanderzz91** [sloria/aiohttp_utils#7]
Hi,

while I was investigating [the other issue I had](https://github.com/sloria/aiohttp_utils/issues/6), I saw in an error traceback that aiohttp_utils actually uses GunicornWebWorker internally:

> File "C:\ProgramData\Anaconda3\envs\sensor_gateway\lib\site-packages\aiohttp_utils\runner.py", line 20, in <module>
>     from aiohttp.worker import GunicornWebWorker as BaseWorker

**Does this mean that I will only be able to deploy my application on Nginx+Gunicorn?** Meaning this limits my deployment options to just one from the 3 deployment ways listed in [aiohttp's deployment documentation section](https://aiohttp.readthedocs.io/en/stable/deployment)?

I saw in that part of the documentation that Nginx+Gunicorn as deployment option can be slightly slower. My app, due its use case, must be FAST.

**Comment by sloria** [comment]
No, this library does not prescribe which web server you use in production. The now-deprecated `runner` module used Gunicorn, but that was only meant to be used in development environments.
